networks:
  appnet:
    name: opensnowcat
    
services:

  warp:
      container_name: warp
      networks:
          appnet:
            aliases: [warp]
      image: public.ecr.aws/warpstream-labs/warpstream_agent:latest
      command:
        - playground
        - -advertiseHostnameStrategy
        - custom
        - -advertiseHostnameCustom
        - warp   
      environment:
        - WARPSTREAM_DISCOVERY_KAFKA_HOSTNAME_OVERRIDE=warp    
      healthcheck:
        test: ["CMD", "sh", "-c", "sleep 10"]
        interval: 5s
        timeout: 15s
        retries: 5

  opensnowcat_collector:
    container_name: opensnowcat_collector
    networks: [ appnet ]
    image: opensnowcat/opensnowcat-collector-kafka:latest
    volumes:
      - ${PWD}/opensnowcat:/opensnowcat
    command: '--config /opensnowcat/config.collector.hocon'
    restart: on-failure
    depends_on:
      - warp
    ports:
      - "8080:8080"   

  opensnowcat_enrich:
    container_name: opensnowcat_enrich
    networks: [ appnet ]  
    image: opensnowcat/opensnowcat-enrich-kafka:latest
    volumes:
      - ${PWD}/opensnowcat:/opensnowcat
    command: '--enrichments /opensnowcat/enrichments --iglu-config /opensnowcat/resolver.json --config /opensnowcat/config.enrich.hocon'
    restart: on-failure
    depends_on:
      - warp
    environment:
      LOG_LEVEL: "INFO"
      JAVA_OPTS: "-Dlogback.configurationFile=/opensnowcat/etc/logback.xml -Dorg.slf4j.simpleLogger.defaultLogLevel=info"

  kafka-ui:
    container_name: kafka-ui
    networks: [ appnet ]  
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    depends_on:
      - warp
    environment:
      - KAFKA_CLUSTERS_0_NAME=Warpstream Kafka Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=warp:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
      - DYNAMIC_CONFIG_ENABLED='true'

  kafka_proxy:
    container_name: kafka_proxy
    networks: [ appnet ]    
    image: alpine/socat
    command: ["-d","-d","TCP-LISTEN:9092,bind=0.0.0.0,fork,reuseaddr","TCP:warp:9092"]
    ports:
      - "9092:9092"
    depends_on:
      - warp

  bento:
    container_name: bento
    networks: [ appnet ]
    image: ghcr.io/warpstreamlabs/bento:latest
    volumes:
      - ./bento:/configs
    command: '-c /configs/tsv-json.yml'
    restart: on-failure
    depends_on:
      - warp
      - opensnowcat_enrich
    environment:
      LOG_LEVEL: "DEBUG"